### ISSUE TITLE
Floating point exception(core dumped)

### ISSUE THREAD

**Issue by nunsie** [sg-dev1/Video_Stream_Player#3]
Hi

I've managed to build the project successfully but get a `Floating point exception(core dumped)` error when trying to run `./prime_video_cli -h`.

Any help getting this up and running would be much appreciated!

**Comment by sg-dev1** [comment]
And you get no other output?
On which Linux distro you are working?

**Comment by nunsie** [comment]
Yeah that’s the only output, I’m running Ubuntu 18.04

**Comment by sg-dev1** [comment]
I have not tried it on Ubuntu. Only tried it on Arch Linux and Manjaro Linux.
There I never got this error.

Yesterday, I tried to run it again, but it seems that Amazon has changed its site and the parsing script seems to be broken again. This issue could be fixed I think quite easily.
However, the bigger issue is that Google has introduced the VMP validation for their Widevine DRM...
See this discussion: https://github.com/sg-dev1/Video_Stream_Player/issues/1

**Comment by nunsie** [comment]
Ah ok I will retry on Arch then, thanks! I'll try update the parsing script and make a pull request if I can get past this error. The VMP is validation thing is a little worrying tho, do you know if it only prevents HD content from playing or all content?

**Comment by sg-dev1** [comment]
My last information regarding VMP validation was that it is only preventing full hd content. But I did not follow this topic further and it is quite some time ago.

**Comment by nunsie** [comment]
Runs like a dream on manjaro! gave me an excuse to checkout the distro as well, its amazing! Will get a PR up soon to update the parsing scripts. Thanks man, closing this issue.
